### ISSUE TITLE
How can we make it easier for people to find parking spots?

### ISSUE THREAD

**Issue by gozie11** [bytesandbrews-smtx/community-problem-sets#8]
-Whole foods has a visual system in their parking garage to show where empty spots are
-Maybe we could have an API that updates the available spots
  -How could we use a computer vision model to implement this
  -How could we use sensor data to capture the cars that enter and exit the stadium parking lot

**Comment by benhprentice** [comment]
Contact TX State about feasibility of implementing this.
Research parking areas at TX State.

**Comment by benhprentice** [comment]
https://www.parking.txst.edu/map.html

**Comment by benhprentice** [comment]
https://uh.edu/af-university-services/parking/blog/2018/jan2018/01122018.php

**Comment by gozie11** [comment]
I'm closing this as the project is now stale.
